package com.idmcore.spa.elastic;

import com.idmcore.spa.SpaRepeat;
import org.springframework.data.elasticsearch.repository.ElasticsearchRepository;

/**
 * Spring data elasticsearch repository, no concrete implementation, is generated by spring.
 */
public interface SpaRepeatCrudRepository extends ElasticsearchRepository<SpaRepeat, String> {
}
