package com.idmcore.spa.elastic;

import com.idmcore.spa.SpaRecord;
import org.springframework.data.elasticsearch.repository.ElasticsearchRepository;

/**
 * Spring data elasticsearch repository, no concrete implementation, is generated by spring.
 */
public interface SpaRecordCrudRepository extends ElasticsearchRepository<SpaRecord, String> {
}
