package com.idmcore.spa.elastic;

import com.idmcore.spa.importer.geo.ZipItem;
import org.springframework.data.elasticsearch.repository.ElasticsearchRepository;

import java.util.List;

/**
 * Spring data elasticsearch repository, no concrete implementation, is generated by spring.
 */
public interface ZipCodeCrudrepository extends ElasticsearchRepository<ZipItem, String> {
    List<ZipItem> findByPostalCodeAndCountry(String isolationZip, String isolationCountryCode);

    List<ZipItem> findByLocalityAndCountry(String isolationCity, String isolationCountryCode);
}
